### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by C0deGyver** [EnigmaBridge/certbot-external-auth#14]
Need more info on how to use this script. I am using the following command: `certbot certonly --agree-tos -m email@domain.com --renew-by-default --no-eff-email -d domain.com -d www.domain.com  -a certbot-external-auth:out --certbot-external-auth:out-public-ip-logging-ok --preferred-challenges dns --certbot-external-auth:out-handler ./certbot-handler.sh`. This results in what looks like information for three text records: token, validation, and key_auth (example below).

`{"cmd": "perform_challenge", "type": "dns-01", "domain": "domain.com", "token": "Xdrw****lNdMtEj****wdLAT****_rIINO6K****wwg", "validation": "IfT2****3t8LP****4TeetW1****6pH2jY****zGgcc", "txt_domain": "_acme-challenge.domain.com", "key_auth": "Xdrw****lNdMtEj****wdLAT****_rIINO6K****wwg.KxGHb****AMkOo****G-****KwmVwC****euPm****s"}`

Am I correct? If not which of these needs to be turned into a text record?

**Comment by C0deGyver** [comment]
I figured it out :). The text record should be the "validation". I am going to fork and create a more complete handler script example.

**Comment by ph4r05** [comment]
Great! Thanks a lot!
