### ISSUE TITLE
Not compatible with current version of certbot

### ISSUE THREAD

**Issue by gtrs** [EnigmaBridge/certbot-external-auth#16]
The TLS-SNI challenge has been removed from the ACME standard. In certbot, the respective parts in the library seem to be gone as well.

certbot-external-auth, however, uses acme.challenges.TLSSNI01 in the line referenced below. 
https://github.com/EnigmaBridge/certbot-external-auth/blob/07eca04bd9ae35ad28e5c184694e0c4e9581fd07/certbot_external_auth/plugin.py#L219

When certbot-external-auth is executed, we get the following error:
```AttributeError: module 'acme.challenges' has no attribute 'TLSSNI01'```

A solution would be to remove everything related to TLS-SNI.

**Comment by dancvrcek** [comment]
We have merged a pull request that removes TLS-SNI from the codel
