### ISSUE TITLE
certbot-external-auth not working with certbot 0.10

### ISSUE THREAD

**Issue by leeyc0** [EnigmaBridge/certbot-external-auth#2]
It appears that certbot.display.util.FileDisplay is changed in [this revision](https://github.com/certbot/certbot/commit/ae379568b12b28112f6798366002f3265d77217e) which introduced an addition argument in it's constructor.

As as result line 165 of certbot_external_auth/plugin.py

`displayer = display_util.FileDisplay(sys.stderr)`

fails. I have to change it to 

`displayer = display_util.FileDisplay(sys.stderr, False)`

to make it work in certbot 0.10

**Comment by ph4r05** [comment]
thanks for letting us know! We will fix it ASAP
