### ISSUE TITLE
types.StringTypes deprecated

### ISSUE THREAD

**Issue by Torxed** [EnigmaBridge/certbot-external-auth#8]
cur_record[FIELD_VALIDATION] = validation if isinstance(validation, types.StringTypes) else ''

in plugin.py, won't work because `StringTypes` is deprecated.

https://docs.python.org/3/library/types.html

**Comment by Torxed** [comment]
Gotta be careful with reimplementing this.
In python3, all data recieved from certbot will be in bytes.

So on 798 in `_json_out()`:

    json_str = json.dumps(data)

will break, because `data` is a Bytes object.
Not really sure why, because when I print `data`, all it shows is:

    OrderedDict([('cmd', 'report'), ('messages', [])])

There's no bytes data in there.

**Comment by Torxed** [comment]
Yepp found it.
It's in there, my debugging skills was not on par apparently.

    OrderedDict([('cmd', 'cleanup'), ('type', 'dns-01'), ('status', 'valid'), ('domain', 'mydomain.se'), ('token', b'some_long_token'), ('validation', 'a_validation_string'), ('key_auth', 'some_key_auth'), ('validated', None), ('error', None)])

`token` is still a bytes object.

    cur_record[FIELD_TOKEN] = b64.b64encode(achall.chall.token)

Fixing. brb.

**Comment by ph4r05** [comment]
Thanks!
