### ISSUE TITLE
acme.jose replaced with josepy (library change upstream)

### ISSUE THREAD

**Issue by Torxed** [EnigmaBridge/certbot-external-auth#9]
https://github.com/EnigmaBridge/certbot-external-auth/blob/master/certbot_external_auth/plugin.py#L33

    from acme.jose import b64

needs to be replaced with

    from josepy import b64

And the library to install is this one:
 * https://github.com/certbot/josepy

Because they're annoying bastards that change even their libraries mid way without any real notification. But hey, I'm just a developer.. What do I know.

(I'll submit a pull request if I got the time this week)

**Comment by ph4r05** [comment]
Thanks!
